import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import './globals.css';

// This should run before the nextjs app is mounted.
import '../lib/startup';
import { SchemaUpdater } from '@/components/app/schema-updater';

// Schema

const figtreeFont = Figtree({
  variable: '--font-figtree',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${figtreeFont.variable} ${figtreeFont.className} relative h-screen w-screen`}
      >
        <main>{children}</main>
        <SchemaUpdater />
      </body>
    </html>
  );
}
